# Generated by Django 6.0.1 on 2026-02-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('last_updated', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'budgets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('relationship', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('last_contact_date', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('morning_mood', models.IntegerField(blank=True, null=True)),
                ('readiness_score', models.IntegerField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('productivity_score', models.IntegerField(blank=True, null=True)),
                ('evening_mood', models.IntegerField(blank=True, null=True)),
                ('diet_quality', models.IntegerField(blank=True, null=True)),
                ('win_of_the_day', models.TextField(blank=True, null=True)),
                ('primary_obstacle', models.TextField(blank=True, null=True)),
                ('hrv', models.IntegerField(blank=True, null=True)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlexibleTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('metric', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flexible_tracker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FocusLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('focus_level', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'focus_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoalParticipants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goal_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('target_date', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteractionParticipants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interaction_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MealLibrary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('default_calories', models.IntegerField(blank=True, null=True)),
                ('default_protein', models.IntegerField(blank=True, null=True)),
                ('default_carbs', models.IntegerField(blank=True, null=True)),
                ('default_fat', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meal_library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'memories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('food_item', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein_g', models.IntegerField(blank=True, null=True)),
                ('carbs_g', models.IntegerField(blank=True, null=True)),
                ('fat_g', models.IntegerField(blank=True, null=True)),
                ('meal_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrition_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('percent_complete', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_stakeholders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProposedAutomations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_condition', models.TextField(blank=True, null=True)),
                ('proposed_action', models.TextField(blank=True, null=True)),
                ('recurrence', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proposed_automations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskAssignees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_assignees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('due_date', models.TextField(blank=True, null=True)),
                ('is_recurring', models.IntegerField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskUpdates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('confidence_level', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_updates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineBlocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.TextField(blank=True, null=True)),
                ('start_datetime', models.TextField(blank=True, null=True)),
                ('end_datetime', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline_blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workouts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField()),
                ('source_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'memory_links',
                'managed': True,
            },
        ),
    ]
