# Generated by Django 6.0.1 on 2026-02-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tool_usage', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('is_archived', models.IntegerField(default=0)),
                ('tags', models.TextField(blank=True, null=True)),
                ('linked_goal_id', models.IntegerField(blank=True, null=True)),
                ('linked_project_id', models.IntegerField(blank=True, null=True)),
                ('linked_contact_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteAttachments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_path', models.TextField()),
                ('file_type', models.TextField()),
                ('uploaded_at', models.TextField()),
            ],
            options={
                'db_table': 'note_attachments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemNotifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('content', models.TextField()),
                ('severity', models.TextField()),
                ('created_at', models.TextField()),
                ('is_read', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'system_notifications',
                'managed': False,
            },
        ),
    ]
